@baseUrl = http://localhost:3000/auth
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MTI2ZDU2ZC1iMzkzLTQzM2YtOWRjMS1mZjUzZTI2NGZiM2QiLCJpYXQiOjE3ODI0MDU5NTMsImV4cCI6MTc4MjQwNjg1M30.rtFWkLQU_krBdzbiitCGGUf3Im2vApwSbcWn2Nbo95o
@idRemove = 722b3641-d237-477c-8289-0494d532af83


### REGISTER
POST {{baseUrl}}/signUp
Content-Type: application/json

{
    "email": "renata@hotmail.com",
    "name": "renata",
    "password": "12345",
    "confirmPassword": "12345"
}

### LOGIN
POST {{baseUrl}}/signIn
Content-Type: application/json

{
    "email": "livia@hotmail.com",
    "password": "pass"
}


### FORGOT PASSWORD

POST {{baseUrl}}/forgot-password
Content-Type: application/json

{
    "email": "vanessa1@example.com"
}

### RESET PASSWORD
POST {{baseUrl}}/reset-password
Authorization: {{token}}
Content-Type: application/json

{
    "newPassword": "pass",
    "confirmPassword": "pass"
}

### GET ME
GET {{baseUrl}}/me
Authorization: {{token}}


### UPDATE ME
PATCH  {{baseUrl}}/me
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Livia Gomes"
}


### UPDATE MY PASSWORD
PATCH  {{baseUrl}}/me/password
Authorization: {{token}}
Content-Type: application/json

{
    "currentPassword": "12345",
    "newPassword": "123456",
    "confirmPassword": "123456"
}

### DELETE ME
DELETE {{baseUrl}}/me
Authorization: {{token}}