@baseUrl = http://localhost:3000/auth
@token = Bearer {{login.response.body.access_token}}


### REGISTER
POST {{baseUrl}}/signUp
Content-Type: application/json

{
    "email": "vanessa1@hotmail.com",
    "name": "vanessa",
    "password": "12345",
    "confirmPassword": "12345"
}


### LOGIN
# @name login
POST {{baseUrl}}/signIn
Content-Type: application/json

{
    "email": "william@hotmail.com",
    "password": "pass"
}


### FORGOT PASSWORD

POST {{baseUrl}}/forgot-password
Content-Type: application/json

{
    "email": "vanessa1@example.com"
}

### RESET PASSWORD
POST {{baseUrl}}/reset-password
Authorization: {{token}}
Content-Type: application/json

{
    "newPassword": "pass",
    "confirmPassword": "pass"
}

