@baseUrl = http://localhost:3000/auth
@token = Bearer {{login.response.body.access_token}}


### REGISTER
POST {{baseUrl}}/signUp
Content-Type: application/json

{
    "email": "livia@hotmail.com",
    "name": "livia",
    "password": "12345",
    "confirmPassword": "12345"
}


### LOGIN
# @name login
POST {{baseUrl}}/signIn
Content-Type: application/json

{
    "email": "livia@hotmail.com",
    "password": "12345"
}


### FORGOT PASSWORD

POST {{baseUrl}}/forgot-password
Content-Type: application/json

{
    "email": "vanessa1@example.com"
}

### RESET PASSWORD
POST {{baseUrl}}/reset-password
Authorization: {{token}}
Content-Type: application/json

{
    "newPassword": "pass",
    "confirmPassword": "pass"
}

### GET ME
GET {{baseUrl}}/me
Authorization: {{token}}


### UPDATE ME
PATCH  {{baseUrl}}/me
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Livia Italia"
}


### UPDATE MY PASSWORD
PATCH  {{baseUrl}}/me/password
Authorization: {{token}}
Content-Type: application/json

{
    "currentPassword": "12345",
    "newPassword": "123456",
    "confirmPassword": "123456"
}

### DELETE ME
DELETE {{baseUrl}}/me
Authorization: {{token}}