@baseUrl = http://localhost:3000/auth
@token = Bearer 722b3641-d237-477c-8289-0494d532af83
@idRemove = 722b3641-d237-477c-8289-0494d532af83


### REGISTER
POST {{baseUrl}}/register
Content-Type: application/json

{
    "email": "vanessa1234@hotmail.com",
    "name": "vanessa",
    "password": "12345",
    "confirmPassword": "12345"
}

### LOGIN
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "vanessa123@example.com",
    "password": "123456"
}


### FORGOT PASSWORD

POST {{baseUrl}}/forgot-password
Content-Type: application/json

{
    "email": "vanessa1@example.com"
}

### RESET PASSWORD
POST {{baseUrl}}/reset-password
Authorization: {{token}}
Content-Type: application/json

{
    "newPassword": "pass",
    "confirmPassword": "pass"
}

### GET ME
GET {{baseUrl}}/me
Authorization: {{token}}


### UPDATE ME
PATCH  {{baseUrl}}/me
Authorization: {{token}}
Content-Type: application/json

{
    "email": "vanessa123456@hotmail.com"
}


### UPDATE MY PASSWORD
PATCH  {{baseUrl}}/me/password
Authorization: {{token}}
Content-Type: application/json

{
    "currentPassword": "pass",
    "newPassword": "123456",
    "confirmPassword": "123456"
}

### DELETE ME
DELETE {{baseUrl}}/me
Authorization: {{token}}