@baseUrl = http://localhost:3000
@id = aa3c0ba4-929b-4b83-8dd1-6bfaf0a4a551
@idRemove = 557075e1-0f81-4126-a365-4d335b1a7c2d

### List Users
GET {{baseUrl}}/users

### Find One User
GET {{baseUrl}}/users/{{id}}

### Create User
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "email": "williamitalia1@hotmail.com",
    "password": "12345"
}

### Update User
PATCH  {{baseUrl}}/users/{{id}}
Content-Type: application/json

{
    "name": "william"
}

### Remove User
DELETE {{baseUrl}}/users/{{idRemove}}

