@baseUrl = http://localhost:3000
@id = f5ca7bc4-2c2e-475b-b5ea-4440270dde7d
@idRemove = 557075e1-0f81-4126-a365-4d335b1a7c2d

### List Users
GET {{baseUrl}}/users

### Find One User
GET {{baseUrl}}/users/{{id}}

### Create User
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "email": "williamitalia1@hotmail.com",
    "password": "12345"
}

### Update User
PATCH  {{baseUrl}}/users/{{id}}
Content-Type: application/json

{
    "email": "williamitalia@hotmail.com",
    "password": "batata123"
}

### Remove User
DELETE {{baseUrl}}/users/{{idRemove}}

