@baseUrl = http://localhost:3000
@id = 5adfc398-79e5-4526-a178-551202321a39
@idRemove = 557075e1-0f81-4126-a365-4d335b1a7c2d

### List Users
GET {{baseUrl}}/users

### Find One User
GET {{baseUrl}}/users/{{id}}

### Create User
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "email": "williamitalia3@hotmail.com",
    "name": "william",
    "password": "12345",
    "passwordConfirm": "12345" 
}

### Update User
PATCH  {{baseUrl}}/users/{{id}}
Content-Type: application/json

{
    "email": "robson@example.com",
    "name": "robson silva"
}

### Remove User
DELETE {{baseUrl}}/users/{{idRemove}}

