@baseUrl = http://localhost:3000
@id = 15c64a66-8ffc-4483-a13c-6ef9b0e037ff
### List Users
GET {{baseUrl}}/users

### Find One User
GET {{baseUrl}}/users/{{id}}

### Create User
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "email": "williamitalia@hotmail.com",
    "password": "1234"
}

### Update User
PATCH  {{baseUrl}}/users/{{id}}
Content-Type: application/json

{
    "email": "williamitalia@hotmail.com",
    "password": "123456"
}

### Remove User
DELETE {{baseUrl}}/users/{{id}}

