@baseUrl = http://localhost:3000
@id = fcf3b32f-c953-4925-8209-4d185d062a18
@idRemove = dc40427b-aa11-4069-af57-519d565abf1d

### List Users
GET {{baseUrl}}/users

### Find One User
GET {{baseUrl}}/users/{{id}}

### Create User
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "email": "williamitalia4@hotmail.com",
    "passwordHash": "1234",
    "tokenHash": "teste"
}

### Update User
PATCH  {{baseUrl}}/users/{{id}}
Content-Type: application/json

{
    "email": "williamitalia@hotmail.com"
}

### Remove User
DELETE {{baseUrl}}/users/{{idRemove}}

