@baseUrl = http://localhost:3000
@id = f6046448-4bbe-498c-9a44-a34a7b5e74f3
@idRemove = 14c4a04e-6088-43bd-aac0-edbb86de6ff0

### List Users
GET {{baseUrl}}/users

### Find One User
GET {{baseUrl}}/users/{{id}}

### Create User
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "email": "williamitalia4@hotmail.com",
    "passwordHash": "1234",
    "tokenHash": "teste"
}

### Update User
PATCH  {{baseUrl}}/users/{{id}}
Content-Type: application/json

{
    "email": "williamitalia@hotmail.com"
}

### Remove User
DELETE {{baseUrl}}/users/{{idRemove}}

